Update README.md
etecs-ru/typedjson pull request #3
Opened 2020-06-06 17:41 UTC by Darkclainer

2020-06-06 20:09 UTC, franchb requested changes
Minor grammatical suggestions introduced.

2020-06-06 20:09 UTC, franchb commented on README.md
> +Imagine, that you send or receive JSON object with some key `config`.
```suggestion
Imagine, that you send or receive a JSON object with some key `config`. 
```

2020-06-06 20:09 UTC, franchb commented on README.md
> +So, the field `Config` in your struct must be able to hold value of two possible types.
```suggestion
So, the field `Config` in your struct must be able to hold a value of two possible types.
```

2020-06-06 20:09 UTC, franchb commented on README.md
> +In this case you basically have next options:
```suggestion
In this case, you have the following options:
```

2020-06-06 20:09 UTC, franchb commented on README.md
> +1. You can declare field `Config` as `interface{}` and somehow determine what type you should expect, assign object of this type to `Config`
```suggestion
1. You can declare field `Config` as `interface{}` and somehow determine what type you should expect, assign an object of this type to `Config` 
```

2020-06-06 20:09 UTC, franchb commented on README.md
> +1. You can implement custom `MarshalJSON`/`UnmarshalJSON` for third type that automatically will handle this cases.
```suggestion
1. You can implement custom `MarshalJSON`/`UnmarshalJSON` for the third type that automatically will handle these cases.
```

2020-06-06 20:09 UTC, franchb commented on README.md
> +This package provides means to generate all boilerplate code for third case.
```suggestion
This package provides means to generate all boilerplate code for the third case.
```

2020-06-06 20:09 UTC, franchb commented on README.md
> +	Name of struct that will used for typed interface (default to %%interface%%Typed.
```suggestion
	Name of the struct that will be used for typed interface (default to `%%interface%%Typed`).
```

2020-06-06 20:09 UTC, franchb commented on README.md
> +Each name in position argument should be name of struct.
```suggestion
Each name in position argument should be the name of the struct. 
```

2020-06-06 20:09 UTC, franchb commented on README.md
> +You can set alias for struct name like this: `foo=*FooConfig`.
```suggestion
You can set an alias for struct name like this: `foo=*FooConfig`.
```

2020-06-06 20:09 UTC, franchb commented on README.md
> +Then you must declare interface that will hold either of these structs.
```suggestion
Then you must declare an interface that will hold either of these structs.
```

2020-06-06 20:09 UTC, franchb commented on README.md
> +The interface must have method `TypedJSON` with special signature.
```suggestion
The interface must have the method `TypedJSON` with a special signature. 
```

2020-06-06 20:09 UTC, franchb commented on README.md
> +This method help compiler to work with types.
```suggestion
This method will advise compiler to work with types.
```

2020-06-07 10:35 UTC, Darkclainer commented on README.md
> +	Name of struct that will used for typed interface (default to %%interface%%Typed.
```suggestion
	The name of the struct that will be used for typed interface (default to `{{interface}}{{Typed}}`).
```

2020-06-07 19:28 UTC, franchb approved these changes

2020-06-07 19:29 UTC, merged